# Generated by Django 4.1.7 on 2023-04-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_question_article_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='lesson',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myApp.question'),
        ),
    ]
