# Generated by Django 4.1.7 on 2023-04-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_answer_lesson_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
