# Generated by Django 4.1.7 on 2023-04-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_answer_img_alter_article_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
